if_unavailable <- function(pkg, expr, envir = parent.frame())
  if (!pkg %in% installed.packages()) invisible(eval(expr, envir = envir))

if_unavailable("devtools", install.packages("devtools"))
if_unavailable("riddlr", devtools::install_github("dgkf/riddlr"))
if_unavailable("shinythemes", install.packages("shinythemes"))
if_unavailable("shinydashboard", install.packages("shinydashboard"))
if_unavailable("shinycssloaders", install.packages("shinycssloaders"))
if_unavailable("dplyr", install.packages("dplyr"))
if_unavailable("tidyr", install.packages("tidyr"))
